version: "3"
services:
  web:
    image: "mrow4a/frontend:latest"
    deploy:
      replicas: 2
      restart_policy:
        condition: "on-failure"
      placement:
        constraints:
            - node.hostname == group32-frontend
    ports:
       - "80:80"
    environment:
      - CC_BACKEND_SERVERS=${CC_BACKEND_SERVERS}
    volumes:
        - "/etc:/hypervisor_etc"
networks:
  webnet: