version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: mrow4a/frontend:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
	networks:
	- webnet
	environment:  
	  - CC_BACKEND_SERVERS = ${CC_BACKEND_SERVERS}
	  - "constraint:node==group32-frontend"
	volumes:
      - "/etc:/hypervisor_etc"
networks:
  webnet: