[[TODO]]
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: stefanstojkovski/cc17-frontend:1.0
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet: