version: "3"
services:
web:
  # replace username/repo:tag with your name and image details
	image: mrow4a/backend:latest
	deploy:
	  replicas: 5
	  restart_policy:
	    condition: on-failure
	ports:
	   - "8000:80"
	networks:
	   - webnet
	environment:
	  - "constraint:node!=group32-frontend"
	volumes:
      - "/etc:/hypervisor_etc"
networks:
  webnet: