version: "3"
services:
  backend:
    image: "mrow4a/backend:latest"
    deploy:
      replicas: 5
      restart_policy:
        condition: "on-failure"
      placement:
        constraints:
            - node.hostname != ${LC_STACK_FRONTEND}
    ports:
      - "8000:80"
    volumes:
        - "/etc:/hypervisor_etc"