version: "3"
services:
  web:
    image: "mrow4a/backend:latest"
    deploy:
      replicas: 5
      restart_policy:
        condition: "on-failure"
      placement:
        constraints:
            - node.hostname != group32-frontend
    ports:
       - "8000:80"
    volumes:
        - "/etc:/hypervisor_etc"
networks:
  webnet: